name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-audit-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-audit-

    - name: Install cargo-audit
      uses: taiki-e/install-action@cargo-audit

    - name: Run cargo audit
      run: cargo audit --json --output audit_results.json

    - name: Upload audit results
      uses: actions/upload-artifact@v3
      with:
        name: audit-results
        path: audit_results.json
        retention-days: 30

  license:
    name: License Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-license
      run: cargo install cargo-license

    - name: Check licenses
      run: |
        echo "Checking dependency licenses..."
        cargo license --json > licenses.json
        
        # Verify we only have approved licenses
        if grep -E '"license": "GPL|AGPL|LGPL"' licenses.json; then
          echo "❌ Found copyleft licenses that may not be compatible"
          exit 1
        else
          echo "✅ All licenses appear compatible"
        fi
        
        # Generate human-readable report
        cargo license > LICENSE_REPORT.txt

    - name: Upload license report
      uses: actions/upload-artifact@v3
      with:
        name: license-report
        path: |
          licenses.json
          LICENSE_REPORT.txt
        retention-days: 30

  supply-chain:
    name: Supply Chain Security
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-deny
      uses: taiki-e/install-action@cargo-deny

    - name: Create cargo-deny config
      run: |
        cat > deny.toml << 'EOF'
        [licenses]
        confidence-threshold = 0.8
        allow = [
            "MIT",
            "Apache-2.0",
            "Apache-2.0 WITH LLVM-exception",
            "BSD-2-Clause",
            "BSD-3-Clause",
            "ISC",
            "Unicode-DFS-2016",
        ]
        deny = [
            "GPL-2.0",
            "GPL-3.0",
            "AGPL-3.0",
            "LGPL-2.1",
            "LGPL-3.0",
        ]

        [bans]
        multiple-versions = "warn"
        skip-tree = []

        [advisories]
        vulnerability = "deny"
        unmaintained = "warn"
        unsound = "warn"
        yanked = "warn"
        EOF

    - name: Run cargo-deny
      run: cargo deny check

  unused-deps:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Install cargo-udeps
      uses: taiki-e/install-action@cargo-udeps

    - name: Check for unused dependencies
      run: cargo +nightly udeps --all-targets